# Generated by Django 4.1.7 on 2023-03-07 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closet', '0002_delete_category_delete_clothingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('TOPS', 'Tops'), ('BOTTOMS', 'Bottoms'), ('DRESSES', 'Dresses'), ('SKIRTS', 'Skirts')], max_length=7)),
                ('brand', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('condition', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
