# Generated by Django 4.1.7 on 2023-03-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='price',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], max_length=2),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1),
        ),
    ]
