# Generated by Django 4.1.7 on 2023-03-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_remove_clothingitem_price_clothingitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
