# Generated by Django 4.1.7 on 2023-03-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_clothingitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/')),
                ('clothing_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closet.clothingitem')),
            ],
        ),
    ]
