# Generated by Django 4.1.7 on 2023-03-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0006_remove_clothingitem_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
