# Generated by Django 4.1.7 on 2023-03-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0007_rename_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='clothing_item',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='closet.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='clothing/'),
        ),
    ]
