# Generated by Django 4.1.7 on 2023-03-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0008_remove_image_clothing_item_clothingitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='color',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='closet.image'),
        ),
    ]
