# Generated by Django 4.1.7 on 2023-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0010_clothingitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('gray', 'gray'), ('white', 'white'), ('ivory', 'ivory'), ('tan', 'tan'), ('brown', 'brown'), ('purple', 'purple'), ('blue', 'blue'), ('teal', 'teal'), ('green', 'green'), ('red', 'red'), ('pink', 'pink'), ('orange', 'orange'), ('yellow', 'yellow')], max_length=10),
        ),
    ]
