# Generated by Django 4.1.7 on 2023-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0011_alter_clothingitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('TOPS', 'Tops'), ('SWEATERS', 'Sweaters'), ('C&J', 'Coats & Jackets'), ('JEANS', 'Jeans'), ('PANTS', 'Pants'), ('BOTTOMS', 'Bottoms'), ('DRESSES', 'Dresses'), ('SKIRTS', 'Skirts'), ('SHORTS', 'Shorts'), ('AW', 'Active Wear'), ('SW', 'Swim Wear'), ('SHOES', 'Shoes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(choices=[('Black', 'black'), ('Gray', 'gray'), ('White', 'white'), ('Ivory', 'ivory'), ('Tan', 'tan'), ('Brown', 'brown'), ('Purple', 'purple'), ('Blue', 'blue'), ('Teal', 'teal'), ('Green', 'green'), ('Red', 'red'), ('Pink', 'pink'), ('Orange', 'orange'), ('Yellow', 'yellow')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=6),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=3),
        ),
    ]
