# Generated by Django 4.1.7 on 2023-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0012_alter_clothingitem_category_alter_clothingitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(choices=[('BL', 'Blouses'), ('BDS', 'Button Down Shirts'), ('KT', 'Knit Tops'), ('TS', 'T Shirt'), ('TT', 'Tank Top'), ('SweatS', 'Sweat Shirt'), ('ST', 'Silk Top'), ('Sless', 'Strapless'), ('HT', 'Halter Tops'), ('Turt', 'Turtlenecks'), ('BS', 'Bodysuits'), ('CROP', 'Cropped')], default='TOPS', max_length=20),
            preserve_default=False,
        ),
    ]
