# Generated by Django 4.1.7 on 2023-03-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0014_clothingitem_selectedtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='image',
        ),
    ]
