# Generated by Django 4.1.7 on 2023-03-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0016_delete_image_clothingitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='selectedTags',
        ),
    ]
