# Generated by Django 4.1.7 on 2023-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0017_remove_clothingitem_selectedtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='selectedTags',
            field=models.JSONField(null=True),
        ),
    ]
