# Generated by Django 4.1.7 on 2023-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0018_clothingitem_selectedtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
    ]
