# Generated by Django 4.1.7 on 2023-03-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0019_alter_clothingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('SWEATERS', 'Sweaters'), ('C&J', 'Coats & Jackets'), ('JEANS', 'Jeans'), ('PANTS', 'Pants'), ('BOTTOMS', 'Bottoms'), ('DRESSES', 'Dresses'), ('SKIRTS', 'Skirts'), ('SHORTS', 'Shorts'), ('AW', 'Active Wear'), ('SW', 'Swim Wear'), ('SHOES', 'Shoes')], max_length=10),
        ),
    ]
