# Generated by Django 4.1.7 on 2023-03-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0020_alter_clothingitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Sweaters', 'Sweaters'), ('Bottoms', 'Bottoms'), ('Dresses', 'Dresses'), ('Skirts', 'Skirts'), ('AW', 'Active Wear'), ('SW', 'Swim Wear'), ('Shoes', 'Shoes')], max_length=10),
        ),
    ]
