# Generated by Django 4.1.7 on 2023-03-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0026_alter_order_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
