# Generated by Django 4.1.7 on 2023-03-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0027_remove_order_is_active_remove_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_active',
        ),
    ]
