# Generated by Django 4.1.7 on 2023-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0028_remove_checkout_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='closet.clothingitem'),
        ),
    ]
