# Generated by Django 4.1.7 on 2023-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0029_order_item_details_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_details',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.JSONField(null=True),
        ),
    ]
