# Generated by Django 4.1.7 on 2023-04-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0031_alter_clothingitem_category_alter_clothingitem_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Sweaters', 'Sweaters'), ('Bottoms', 'Bottoms'), ('Pants', 'Pants'), ('Dresses', 'Dresses'), ('Skirts', 'Skirts'), ('Active Wear', 'Active Wear'), ('Swim Wear', 'Swim Wear'), ('Shoes', 'Shoes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(choices=[('Blouses', 'Blouses'), ('Button Down Shirts', 'Button Down Shirts'), ('T-Shirt', 'T Shirt'), ('Tank Tops', 'Tank Top'), ('Short Sleeve', 'Short Sleeve'), ('Long Sleeve', 'Long Sleeve'), ('Sweat Shirts', 'Sweat Shirt'), ('Sweaters', 'Sweater'), ('Cardigans', 'Cardigan'), ('Jackets', 'Jacket'), ('Coats', 'Coat'), ('Strapless', 'Strapless'), ('Halter Tops', 'Halter Tops'), ('Turtlenecks', 'Turtlenecks'), ('Crop Tops', 'Crop Tops'), ('Pants', 'Pants'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Dresses', 'Dresses'), ('Leggings', 'Leggings'), ('Joggers', 'Joggers'), ('Sweat Pants', 'Sweat Pants'), ('Sweat Shorts', 'Sweat Shorts'), ('Sweat Suits', 'Sweat Suit'), ('Swim Suits', 'Swim Suit'), ('Bikinis', 'Bikini'), ('One Piece', 'One Piece'), ('Cover Ups', 'Cover Up')], max_length=20),
        ),
    ]
