# Generated by Django 4.1.7 on 2023-04-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0034_alter_clothingitem_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Sweaters', 'Sweaters'), ('Bottoms', 'Bottoms'), ('Pants', 'Pants'), ('Dresses', 'Dresses'), ('Skirts', 'Skirts'), ('Active_Wear', 'Active Wear'), ('Swim_Wear', 'Swim Wear'), ('Shoes', 'Shoes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(choices=[('Blouses', 'Blouses'), ('Button_Down_Shirts', 'Button Down Shirts'), ('T_Shirt', 'T Shirt'), ('Tank_Tops', 'Tank Top'), ('Short_Sleeve', 'Short Sleeve'), ('Long_Sleeve', 'Long Sleeve'), ('Sweat_Shirts', 'Sweat Shirt'), ('Sweaters', 'Sweater'), ('Cardigans', 'Cardigan'), ('Jackets', 'Jacket'), ('Coats', 'Coat'), ('Strapless', 'Strapless'), ('Halter Tops', 'Halter Tops'), ('Turtlenecks', 'Turtlenecks'), ('Crop_Tops', 'Crop Tops'), ('Pants', 'Pants'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Dresses', 'Dresses'), ('Mini_Dresses', 'Mini Dresses'), ('Maxi_Dresses', 'Maxi Dresses'), ('Midi_Dresses', 'Midi Dresses'), ('Sheath_Dresses', 'Sheath Dresses'), ('Shift_Dresses', 'Shift Dresses'), ('Wrap_Dresses', 'Wrap Dresses'), ('T_Shirt_Dresses', 'T Shirt Dresses'), ('Sweater_Dresses', 'Sweater Dresses'), ('Leggings', 'Leggings'), ('Joggers', 'Joggers'), ('Sweat_Pants', 'Sweat Pants'), ('Sweat_Shorts', 'Sweat Shorts'), ('Rompers', 'Rompers'), ('Swim_Suits', 'Swim Suit'), ('Bikinis', 'Bikini'), ('One_Piece', 'One Piece'), ('Cover_Up', 'Cover Up'), ('Beach_Dresses', 'Beach Dresses'), ('Boots', 'Boots'), ('Heels', 'Heels'), ('Sandals', 'Sandals'), ('Flats', 'Flats'), ('Sneakers', 'Sneakers'), ('Slippers', 'Slippers'), ('Flip_Flops', 'Flip Flops'), ('Wedges', 'Wedges'), ('high_Heels', 'High Heels'), ('high_tops', 'High Tops'), ('low_tops', 'Low Tops'), ('mid_tops', 'Mid Tops'), ('wing_tips', 'Wing Tips'), ('oxfords', 'Oxfords'), ('loafers', 'Loafers'), ('moccasins', 'Moccasins'), ('slip_ons', 'Slip Ons')], max_length=20),
        ),
    ]
