# Generated by Django 4.1.7 on 2023-03-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TM', 'Trans Male'), ('TF', 'Trans Female'), ('NB', 'Non Binary'), ('GNC', 'Gender Non Conforming'), ('GF', 'Gender Fluid'), ('GQ', 'Gender Queer'), ('IS', 'Intersex'), ('NA', 'Other')], default='NA', max_length=3),
            preserve_default=False,
        ),
    ]
