# Generated by Django 4.1.7 on 2023-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('TM', 'Trans Male'), ('TF', 'Trans Female'), ('NB', 'Non Binary'), ('GNC', 'Gender Non Conforming'), ('GF', 'Gender Fluid'), ('GQ', 'Gender Queer'), ('IS', 'Intersex'), ('NA', 'Other')], max_length=3, null=True),
        ),
    ]
