# Generated by Django 4.1.7 on 2023-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0022_checkout'),
        ('accounts', '0005_profile_avatar_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ClothingItem',
            field=models.ManyToManyField(blank=True, to='closet.clothingitem'),
        ),
    ]
