# Generated by Django 4.1.7 on 2023-03-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_city_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ClothingItem',
        ),
    ]
