# Generated by Django 4.1.7 on 2023-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans Male', 'Trans Male'), ('Trans Female', 'Trans Female'), ('Non Binary', 'Non Binary'), ('GNC', 'Gender Non Conforming'), ('NA', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans Male', 'Trans Male'), ('Trans Female', 'Trans Female'), ('Non Binary', 'Non Binary'), ('GNC', 'Gender Non Conforming'), ('NA', 'Other')], max_length=20),
        ),
    ]
