# Generated by Django 4.1.7 on 2023-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_gender_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans Male', 'Trans Male'), ('Trans Female', 'Trans Female'), ('Non Binary', 'Non Binary'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans Male', 'Trans Male'), ('Trans Female', 'Trans Female'), ('Non Binary', 'Non Binary'), ('Other', 'Other')], max_length=20),
        ),
    ]
